language: haskell

ghc:
  - 7.8

before_install:
  - git clone https://github.com/haskell-servant/servant.git
  - cabal sandbox init
  - cabal sandbox add-source servant/

notifications:
  irc:
    channels:
      - "irc.freenode.org#servant"
    template:
      - "%{repository}#%{build_number} - %{commit} on %{branch} by %{author}: %{message}"
      - "Build details: %{build_url} - Change view: %{compare_url}"
    skip_join: true
    on_success: change
    on_failure: always
